"""
Django settings for yozex project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
from django.conf import settings
import dj_database_url
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
#BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7v4d2fw&%cdgku-sntv1o%s(r6nw8=jq!!8l_j-%(0#-wigmy5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

#CSRF_TRUSTED_ORIGINS = ['http://example.com']
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'modules.users.apps.UsersConfig',
    'modules.categories.apps.CategoriesConfig',
    'modules.locations.apps.LocationsConfig',
    'modules.posts.apps.PostsConfig',
    'modules.cms_managements.apps.CmsManagementsConfig',
    'modules.feedbacks.apps.FeedbacksConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = True

CORS_URLS_REGEX = r'^/(en|pt-br)/api/v1/.*$'

ROOT_URLCONF = 'yozex.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = (

    'django.contrib.auth.backends.ModelBackend',
)
ASGI_APPLICATION = 'yozex.routing.application'
WSGI_APPLICATION = 'yozex.wsgi.application'


REST_FRAMEWORK = {
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FileUploadParser',
    ],
    'DEFAULT_PERMISSION_CLASSES': (
     'rest_framework.permissions.IsAuthenticated' ,
     ),
    #'EXCEPTION_HANDLER': 'ServiceProvider.utils.custom_exception_handler',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        #'rest_framework.authentication.BasicAuthentication',
        #'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication'
    ],
    'DEFAULT_RENDERER_CLASSES': [
        #'ServiceProvider.custom_jsonrender.render',
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',        
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 10,
    # 'CUSTOM_JSONRender':[
    #     'ServiceProvider.custom_jsonrender.CustomJSONRenderer.render'
    # ]
    "DATETIME_INPUT_FORMATS": [
              '%Y-%m-%d %H:%M:%S',     # '2006-10-25 14:30:59'
              '%Y-%m-%d %H:%M:%S.%f',  # '2006-10-25 14:30:59.000200'
              '%Y-%m-%d %H:%M',        # '2006-10-25 14:30'
              '%Y-%m-%d',              # '2006-10-25'
              '%m/%d/%Y %H:%M:%S',     # '10/25/2006 14:30:59'
              '%m/%d/%Y %H:%M:%S.%f',  # '10/25/2006 14:30:59.000200'
              '%m/%d/%Y %H:%M',        # '10/25/2006 14:30'
              '%m/%d/%Y',              # '10/25/2006'
              '%m/%d/%y %H:%M:%S',     # '10/25/06 14:30:59'
              '%m/%d/%y %H:%M:%S.%f',  # '10/25/06 14:30:59.000200'
              '%m/%d/%y %H:%M',        # '10/25/06 14:30'
              '%m/%d/%y',              # '10/25/06'
              '%d %B %Y %I:%M %p',      #  '09 September 2019 07:00 AM'
              '%d-%m-%Y',
              '%d/%m/%Y',
              '%d %B %Y %H:%M',        # '09 November 2019 13:00'
              
          ],
}
# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
#server database
DATABASES = {
    'default': dj_database_url.config(conn_max_age=600)
 
    # {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'd6bt24t684e7o4',
    #     'USER': 'hlloexkzwilghy',
    #     'PASSWORD':'948f1879ac3db8f94b2726ec2e9a3d1ca6a8203298d627493e76b49d9155ade2',
    #     'HOST':'ec2-3-223-169-166.compute-1.amazonaws.com',
    #     'PORT':'5432',
    # }
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'yozex',
#         'USER': 'yozex',
#         'PASSWORD':'GiKzrTJEd4Az',
#         'HOST':'127.0.0.1',
#         'PORT':'5432',
#     }
# }
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'yozex_devlopment',
#         'USER': 'postgres',
#         'PASSWORD':'12345',
#         'HOST':'127.0.0.1',
#         'PORT':'5432',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
#AUTH_USER_MODEL = 'users.UserProfile'
#AUTH_USER_MODULE = 'yozex.User'
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field
#STATICFILES_DIRS=[BASE_DIR,"static"]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
