# Generated by Django 4.0 on 2022-07-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(choices=[('ABOUT US', 'About us'), ('PRIVACY', 'Privacy Policy'), ('TERMS AND CONDITIONS', 'Terms & Conditions'), ('FAQ', 'Faq'), ('HELP', 'Help')], max_length=50, unique=True)),
                ('short_description', models.TextField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Static page',
                'verbose_name_plural': 'Static Pages',
            },
        ),
    ]
